spring:
  application:
    name: back

  datasource:
    url: jdbc:mysql://localhost:3306/simpleDb__test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root123414
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true